name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 当推送到main分支时触发
  pull_request:
    branches:
      - main # 当对main分支提交PR时触发
  workflow_dispatch: # 支持手动触发

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Deploy
        uses: actions/deploy-pages@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
